[package]
name = "QRcode_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode = "0.14.0"
image = "0.25.1"
proconio = "0.5.0"